export type KnowledgeArticle = {
  slug: string;
  category: string;
  title: string;
  text: string;
  body: readonly string[];
  headings: readonly string[];
  image: string;
  alt: string;
  source: string;
  sourceLabel: string;
  updated?: string;
};

const repository = "https://github.com/MaartenDominicus/TroosCom";
const suggestions = `${repository}/blob/main/blog%20post%20suggestions.txt`;

export const knowledgeArticlesNl = [
  {
    slug: "veilige-elektrische-installatie",
    category: "Elektra · 6 min",
    title: "Oudere elektrische installatie: waar let u op?",
    text: "Van groepenkast en aarding tot oude bedrading: dit zijn de onderdelen die samen de veiligheid en capaciteit bepalen.",
    body: [
      "Een oudere elektrische installatie hoeft niet automatisch onveilig te zijn, maar vraagt wel om een beoordeling als u gaat verbouwen of meer apparatuur gaat gebruiken. De groepenkast verdeelt de woning over afzonderlijke groepen. Automaten beveiligen tegen overbelasting en kortsluiting; aardlekbeveiliging is een aanvullende bescherming wanneer stroom via een ongewenste weg wegvloeit.",
      "Kijk niet alleen naar de kast. Aarding, kabels, verbindingen en leidingroutes vormen samen één installatie. In oudere woningen kunnen verbindingen los of aangetast zijn en kan de isolatie van bedrading zijn verouderd. Plaatselijk oplappen is dan niet altijd de meest verstandige oplossing: soms is een nieuw, overzichtelijk leidingtracé veiliger en beter uit te breiden.",
      "De benodigde capaciteit hangt af van het gelijktijdige gebruik. Inductiekoken, een oven, warmtepomp, laadpunt of andere zware verbruikers kunnen een aparte groep of een aanpassing van de aansluiting nodig maken. Bepaal daarom eerst wat u nu gebruikt en wat u later wilt toevoegen, voordat wanden en vloeren worden afgewerkt.",
      "Ook de afwerking is een keuze. Inbouw is strak, maar vraagt vaak om frezen en herstelwerk. Opbouw is voordeliger en beter bereikbaar. Via een kruipruimte of bestaande schacht kan soms een nette route worden gemaakt met minder breekwerk. Een installatieplan verbindt dus veiligheid, gebruik en afwerking.",
      "Laat wijzigingen en uitbreidingen ontwerpen, aansluiten en controleren door een vakbekwaam installateur. NEN 1010 is de centrale Nederlandse norm voor nieuwe laagspanningsinstallaties en voor wijzigingen en uitbreidingen. Bij een bestaande installatie kan een uitbreiding ertoe leiden dat ook het beïnvloede bestaande deel moet worden aangepast.",
    ],
    headings: ["Begin bij het geheel", "Controleer meer dan de groepenkast", "Breng toekomstig verbruik in kaart", "Kies een passende kabelroute", "Laat aanpassingen controleren"],
    image: "/blog/hoofdschakelaar.jpg",
    alt: "Hoofdschakelaar in een bestaande groepenkast",
    source: `${repository}/blob/main/electriciteit.html`,
    sourceLabel: "Bronartikel Elektra uit het openbare projectarchief",
    updated: "Inhoud gecontroleerd aan de hand van NEN-informatie over NEN 1010.",
  },
  {
    slug: "binnendeuren-hang-en-sluitwerk",
    category: "Binnendeuren · 5 min",
    title: "Hang- en sluitwerk in oudere woningen",
    text: "Doorhangende klinken, afwijkende slotmaten en versleten scharnieren vragen vaak om maatwerk in plaats van een standaardvervanging.",
    body: [
      "Een doorhangende deurklink komt bij oudere deuren vaak voor. Een moderne, zwaardere hendel belast de veer van een oud slot meer dan het oorspronkelijke lichte beslag. Een geveerde deurkruk kan helpen, mits het hout rondom het slot sterk genoeg is voor een degelijke bevestiging. Is het slot zelf versleten, dan is volledige vervanging meestal duurzamer.",
      "Bij oude sloten wijken doornmaat, voorplaat en uitsparingen geregeld af van moderne standaarden. Kies daarom eerst een nieuw slot dat de bestaande maatvoering zo dicht mogelijk benadert. Grote verschillen betekenen dat gaten moeten worden gevuld, opnieuw geboord of uitgefreesd. Houd dan ook rekening met herstel van het schilderwerk.",
      "Een vrij-bezetsluiting in een badkamer of toilet vraagt vaak om een ander type insteekslot en extra freeswerk. Ook de sluitplaat in het kozijn moet meestal worden aangepast. Een slot is pas goed vervangen wanneer de deur zonder spanning sluit, de dagschoot netjes aangrijpt en het beslag stabiel blijft.",
      "Versleten scharnieren kunnen een deur laten zakken. Moderne, geschroefde scharnieren zijn vaak relatief eenvoudig te vervangen. Oude of ingebouwde uitvoeringen zijn soms niet meer leverbaar en moeten worden verwijderd, waarna deur en kozijn passend worden gemaakt voor nieuwe scharnieren. Dat is precies het soort werk waarbij de staat van het bestaande hout de aanpak bepaalt.",
      "Een compleet nieuwe deur is niet altijd de snelste uitweg. Oude kozijnen zijn zelden perfect recht, waardoor een nieuwe rechte deur niet vanzelf mooi aansluit. Soms is vervanging van deur én kozijn nodig. Voor betere geluidsisolatie kunnen een massieve deur, kierdichting en eventueel een valdorpel meer effect hebben dan alleen nieuw beslag.",
    ],
    headings: ["Onderzoek waarom de klink hangt", "Meet het bestaande slot nauwkeurig", "Stem slot en sluitplaat op elkaar af", "Beoordeel deur en scharnieren samen", "Kijk verder dan alleen het beslag"],
    image: "/blog/doorhangende-deurhendel.jpg",
    alt: "Doorhangende deurhendel op een oudere binnendeur",
    source: `${repository}/blob/main/Binnendeuren_hang_en_sluitwerk.html`,
    sourceLabel: "Bronartikel Binnendeuren en hang- en sluitwerk uit het openbare projectarchief",
  },
  {
    slug: "tegels-en-voegen-kiezen",
    category: "Badkamer · 7 min",
    title: "Tegels en voegen kiezen voor de badkamer",
    text: "Formaat, maatvastheid, voegbreedte en ondergrond bepalen samen hoe strak het tegelwerk wordt én hoeveel onderhoud het vraagt.",
    body: [
      "Grote tegels geven een rustig beeld, hebben minder voegen en zijn daardoor vaak makkelijker schoon te houden. Ze vragen wel om een vlakke ondergrond. Kleinere tegels volgen een licht golvende wand eenvoudiger, maar zorgen voor meer voegwerk. In een kleine ruimte moet u dus zoeken naar de balans tussen vlak maken, ruimteverlies en het gewenste formaat.",
      "Het legverband beïnvloedt zowel uitstraling als arbeidsduur. Een recht verband is overzichtelijk; halfsteens of diagonale patronen vragen meer uitlijning en snijwerk. Bij een sterk contrasterende voegkleur vallen kleine verschillen in tegelmaat en voegbreedte extra op. Maak daarom vooraf een legplan met zichtlijnen, hoeken, nissen en aansluitingen.",
      "Gerectificeerde tegels zijn na productie nauwkeuriger op maat gemaakt en kunnen doorgaans met een strakkere voeg worden verwerkt. Ook deze tegels hebben toleranties. Niet-gerectificeerde of handgevormde tegels vragen meestal om bredere voegen, zodat maatverschillen netjes kunnen worden verdeeld. Controleer behalve lengte en breedte ook dikte, haaksheid en eventuele kromming.",
      "Voor vloeren is een matte, daarvoor geschikte tegel meestal praktisch: glanzende oppervlakken kunnen glad zijn en wandtegels zijn niet automatisch sterk genoeg voor de vloer. Natuursteen en ongeglazuurde tegels kunnen extra gevoelig zijn voor vocht, vlekken of schoonmaakmiddelen en vragen soms om impregneren en onderhoud.",
      "Cementgebonden voegmortel is gangbaar en voordelig, maar kan gevoeliger zijn voor verkleuring en vuil. Reactiehars- of composietvoegen zijn duurder, maar kunnen in intensief gebruikte of licht gevoegde vloeren makkelijker te onderhouden zijn. Kies voeg- en kitkleur samen; elke extra kleurwisseling kost meer tijd en maakt kleine afwijkingen zichtbaarder.",
      "Werk in natte ruimtes begint altijd onder de tegel. Een stabiele, vlakke ondergrond, correcte waterdichting, goede afschotvorming en nette aansluitingen bij dorpel, afvoer en leidingdoorvoeren bepalen de levensduur. Leg materiaalkeuzes en detaillering daarom vast vóórdat de tegelzetter start.",
    ],
    headings: ["Kies formaat op basis van de ondergrond", "Maak eerst een legplan", "Let op maatvastheid", "Kies een tegel die past bij het gebruik", "Vergelijk voegmaterialen", "Begin onder de tegel"],
    image: "/blog/badkamer-tegels.jpg",
    alt: "Badkamer met tegelwerk uit het eigen projectarchief",
    source: `${repository}/blob/main/tilesandgrout.html`,
    sourceLabel: "Bronartikel Tiles and Grout uit het openbare projectarchief",
  },
  {
    slug: "verborgen-waterlek-opsporen",
    category: "Water & sanitair · 6 min",
    title: "Een verborgen waterlek herkennen voordat de schade groeit",
    text: "Een hogere waterrekening, muffe lucht of een koude vochtplek kan het eerste signaal zijn. Zo brengt u de situatie veilig en doelgericht in kaart.",
    body: [
      "Een verborgen lekkage laat zich zelden direct zien. Let op een onverwacht hoger waterverbruik, verkleuring van stuc- of schilderwerk, loslatende plinten, schimmelvorming en een plek die langdurig koud of vochtig blijft. Eén signaal bewijst nog niets, maar meerdere signalen op dezelfde locatie zijn reden om snel verder te kijken.",
      "Controleer eerst of er water wordt gebruikt en noteer daarna de stand van de watermeter. Verandert de meter terwijl kranen, apparaten en toiletten niet vullen, dan kan er sprake zijn van ongewenst verbruik. Sluit apparaten en deelkranen alleen af wanneer u weet hoe dat veilig moet; zo kan een installateur later gerichter bepalen in welk deel van het systeem het probleem zit.",
      "De zichtbare vochtplek ligt niet altijd direct bij de bron. Water kan langs een leiding, balk of vloerrand lopen voordat het naar buiten treedt. Open daarom niet willekeurig een wand of plafond. Met gerichte metingen, drukcontrole en kennis van leidingroutes kan het zoekgebied vaak eerst worden verkleind.",
      "Beperk in de tussentijd de schade. Draai bij een actieve lekkage de hoofdkraan dicht, schakel elektrische groepen in het natte gebied uit wanneer dat zonder risico kan en verplaats kwetsbare spullen. Maak foto's van de situatie en noteer wanneer het probleem zichtbaar werd; die informatie helpt bij herstel en een eventuele schademelding.",
      "Na het repareren van de leiding is het werk nog niet altijd klaar. Materialen moeten gecontroleerd drogen en aangetaste afwerking kan pas daarna duurzaam worden hersteld. Laat ook de oorzaak beoordelen, bijvoorbeeld een slechte verbinding, slijtage, beweging of vorst, zodat dezelfde lekkage niet op een andere plek terugkomt.",
    ],
    headings: ["Herken de vroege signalen", "Gebruik de watermeter als eerste controle", "Zoek niet alleen bij de vochtplek", "Beperk verdere schade", "Herstel ook de oorzaak"],
    image: "/projects/riolering-apeldoorn.webp",
    alt: "Leidingwerk tijdens installatiewerk in Apeldoorn",
    source: suggestions,
    sourceLabel: "Onderwerp gebaseerd op suggesties uit het openbare projectarchief",
    updated: "Praktische gids van Domi Installatie.",
  },
  {
    slug: "warmwatertoestel-kiezen",
    category: "Verwarming · 7 min",
    title: "Welk warmwatertoestel past bij uw woning?",
    text: "Een voorraadvat, doorstromer of warmtepompboiler vraagt om een andere afweging van comfort, ruimte, energie en installatie.",
    body: [
      "Begin niet bij het merk of vermogen, maar bij uw warmwaterprofiel. Hoeveel mensen wonen er in huis, hoeveel douches worden kort na elkaar gebruikt en is er tegelijk warm water nodig in keuken en badkamer? Het piekmoment bepaalt vaak meer dan het gemiddelde verbruik.",
      "Een toestel met voorraadvat levert gedurende een bepaalde tijd veel warm water, maar neemt ruimte in en verliest ook buiten gebruik warmte. Een doorstroomtoestel verwarmt wanneer er vraag is en heeft geen groot vat, maar stelt hogere eisen aan de beschikbare elektrische of gascapaciteit. Een warmtepompboiler gebruikt omgevingswarmte en vraagt voldoende opstelruimte, luchttoevoer en aandacht voor geluid en condensafvoer.",
      "Controleer wat de woning technisch aankan. De elektrische aansluiting, groepenkast, rookgas- of ventilatievoorziening, leidingdiameters en afstand tot tappunten kunnen de keuze beperken. Een toestel dicht bij de belangrijkste tappunten vermindert wachttijd en leidingverlies, maar moet wel veilig bereikbaar blijven voor onderhoud.",
      "Vergelijk niet alleen de aanschafprijs. Neem installatieaanpassingen, verwacht energiegebruik, onderhoud, levensduur en eventueel ruimteverlies mee. Een efficiënt toestel dat slecht bij het gebruikspatroon past, kan alsnog minder comfortabel of onnodig duur zijn.",
      "Laat de uiteindelijke keuze baseren op een opname van de woning en een berekening van de warmwaterbehoefte. Vraag om een voorstel waarin capaciteit, opwarmtijd, beschikbare infrastructuur en toekomstplannen duidelijk zijn benoemd. Zo kiest u een systeem dat niet alleen vandaag, maar ook na een verbouwing of gezinsverandering past.",
    ],
    headings: ["Breng uw piekgebruik in beeld", "Vergelijk de drie hoofdtypen", "Controleer de technische randvoorwaarden", "Bereken de totale kosten", "Kies op basis van woning én toekomst"],
    image: "/projects/vloerverwarming-kampen.webp",
    alt: "Verwarmingsinstallatie en leidingwerk in Kampen",
    source: suggestions,
    sourceLabel: "Onderwerp gebaseerd op suggesties uit het openbare projectarchief",
    updated: "Keuzehulp van Domi Installatie.",
  },
  {
    slug: "signalen-elektrische-problemen",
    category: "Elektra · 6 min",
    title: "Vijf signalen dat uw elektrische installatie aandacht vraagt",
    text: "Knipperende verlichting, warme contactdozen en terugkerende uitval zijn geen details. Ze vertellen iets over belasting, verbindingen of beveiliging.",
    body: [
      "Verlichting die herhaaldelijk knippert of dimt kan wijzen op een losse verbinding, een defect armatuur of spanningsvariatie wanneer een zwaar apparaat inschakelt. Noteer wanneer het gebeurt en welke apparaten op dat moment actief zijn. Dat patroon helpt om onderscheid te maken tussen één lichtpunt en een breder installatieprobleem.",
      "Een stekker, contactdoos of schakelaar hoort niet opvallend warm te worden, te verkleuren of naar verbrand materiaal te ruiken. Stop het gebruik zodra u zulke signalen ziet. Trek een stekker alleen uit wanneer dat veilig kan en laat het betreffende punt controleren voordat het opnieuw wordt belast.",
      "Een automaat of aardlekschakelaar die uitschakelt, doet dat om een reden. Een eenmalige overbelasting is iets anders dan terugkerende uitval bij hetzelfde apparaat of dezelfde groep. Blijf een beveiliging niet steeds opnieuw inschakelen zonder de oorzaak te kennen; daarmee verdwijnt de storing niet.",
      "Losse contactdozen, beschadigde snoeren en veel gekoppelde stekkerdozen vergroten de kans op slechte verbindingen en overbelasting. Tijdelijke verlengkabels zijn geen vervanging voor voldoende vaste aansluitpunten. Bij een nieuwe indeling of extra apparatuur is een planmatige uitbreiding meestal netter en veiliger.",
      "Laat de installatie beoordelen wanneer meerdere signalen samen optreden, bij aankoop van een oudere woning of vóór een grotere verbouwing. Een vakbekwame inspectie kijkt naar verdeling, beveiliging, aarding, verbindingen en de voorgenomen belasting. Zo wordt niet alleen het zichtbare symptoom, maar het samenhangende systeem aangepakt.",
    ],
    headings: ["Knipperende of dimmende verlichting", "Warmte, verkleuring of brandlucht", "Beveiligingen die terugkerend uitschakelen", "Losse punten en te veel stekkerdozen", "Laat het systeem als geheel beoordelen"],
    image: "/projects/renovatie-rotterdam.webp",
    alt: "Afwerking en installatiewerk tijdens een renovatie in Rotterdam",
    source: suggestions,
    sourceLabel: "Onderwerp gebaseerd op suggesties uit het openbare projectarchief",
    updated: "Veiligheidsinformatie van Domi Installatie.",
  },
  {
    slug: "badkamerventilator-kiezen",
    category: "Ventilatie · 6 min",
    title: "Een badkamerventilator kiezen: capaciteit, geluid en regeling",
    text: "Goede ventilatie voert vocht af zonder dat comfort of rust verloren gaat. Deze keuzes bepalen of het systeem in de praktijk werkt.",
    body: [
      "Een badkamer produceert in korte tijd veel vocht. Zonder voldoende afvoer blijft dat vocht op spiegels, kitnaden, wanden en plafonds achter. Een ventilator moet daarom niet alleen bij de ruimte passen, maar ook lang genoeg blijven draaien om de vochtpiek na het douchen af te voeren.",
      "De benodigde capaciteit hangt samen met het volume van de ruimte, de lengte en weerstand van het kanaal en de beschikbare toevoer van droge lucht. Een krachtige ventilator presteert slecht wanneer de deur volledig afsluit of het kanaal veel bochten en vernauwingen heeft. Toevoer en afvoer moeten als één luchtstroom worden ontworpen.",
      "Let bij de keuze op geluid in de werkelijke opstelling. Een stille motor helpt, maar trillingen, een te smal kanaal of een slecht bevestigde terugslagklep kunnen alsnog geluid veroorzaken. Plaatsing, kanaalmateriaal en montage zijn daarom net zo belangrijk als de waarde op de verpakking.",
      "Een nalooptimer laat de ventilator na gebruik doorwerken. Een vochtsensor reageert op stijgende luchtvochtigheid en kan handig zijn wanneer gebruikers vergeten de ventilatie in te schakelen. Koppeling aan het licht is eenvoudig, maar geeft niet altijd de juiste draaitijd. Kies de regeling die past bij het gebruik van de ruimte.",
      "Controleer ook waar de lucht naartoe gaat. Afvoer naar een afgesloten zolder of kruipruimte verplaatst het vochtprobleem. Gebruik een geschikte route naar buiten of sluit correct aan op het aanwezige ventilatiesysteem. Laat elektrische aansluitingen in de badkamer uitvoeren met aandacht voor de veilige zones en de geschiktheid van het toestel.",
    ],
    headings: ["Voer de vochtpiek echt af", "Bereken meer dan alleen kamervolume", "Beperk geluid bij de bron", "Kies een passende regeling", "Maak de afvoerroute compleet"],
    image: "/projects/badkamer-amsterdam.webp",
    alt: "Afgewerkte badkamer in Amsterdam",
    source: suggestions,
    sourceLabel: "Onderwerp gebaseerd op suggesties uit het openbare projectarchief",
    updated: "Praktische ventilatiegids van Domi Installatie.",
  },
  {
    slug: "leidingnoodgeval-eerste-stappen",
    category: "Onderhoud · 5 min",
    title: "Lekkage of gesprongen leiding: wat doet u als eerste?",
    text: "Een rustige volgorde beperkt water- en gevolgschade. Dit kunt u doen voordat professionele hulp arriveert.",
    body: [
      "Breng eerst uzelf en anderen in veiligheid. Kom niet in water te staan wanneer elektrische apparatuur, stopcontacten of verdeelinrichtingen nat kunnen zijn. Is er acuut gevaar, een gaslucht of een grote oncontroleerbare situatie, verlaat dan de ruimte en schakel de juiste hulpdienst in.",
      "Stop vervolgens de watertoevoer. De hoofdkraan zit vaak bij de watermeter, maar de exacte locatie verschilt per woning. Zorg dat alle bewoners vooraf weten waar deze zit en controleer af en toe of hij bedienbaar is. Bij een lokaal toestel kan een aparte afsluiter soms voldoende zijn.",
      "Beperk verspreiding met bakken en absorberend materiaal en verplaats meubels, elektronica en waardevolle spullen. Prik niet zomaar een nat plafond open: opgehoopt water en los materiaal kunnen onverwacht naar beneden komen. Houd mensen uit de gevarenzone totdat de constructie is beoordeeld.",
      "Leg de situatie vast met foto's en korte notities, maar stel veiligheid boven documentatie. Noteer wanneer de lekkage begon, welke kraan is gesloten en welke ruimtes zijn geraakt. Geef bij het bellen duidelijk door of het water nog stroomt, waar de afsluiter zit en of elektra mogelijk betrokken is.",
      "Een noodreparatie stopt de directe lekkage; daarna volgt droging en herstel. Laat controleren welke materialen nat zijn geworden en of leidingverbindingen, isolatie, vloeren of wanden vervolgwerk nodig hebben. Maak ten slotte een eenvoudig noodkaartje met locaties van hoofdkranen, groepenkast en belangrijke telefoonnummers.",
    ],
    headings: ["Controleer eerst op direct gevaar", "Sluit de watertoevoer af", "Beperk verspreiding zonder extra risico", "Documenteer de situatie gericht", "Plan droging en definitief herstel"],
    image: "/projects/riolering-apeldoorn.webp",
    alt: "Installatiewerk aan leidingen in Apeldoorn",
    source: suggestions,
    sourceLabel: "Onderwerp gebaseerd op suggesties uit het openbare projectarchief",
    updated: "Noodstappenplan van Domi Installatie.",
  },
] as const satisfies readonly KnowledgeArticle[];

export const knowledgeArticlesEn = [
  {
    ...knowledgeArticlesNl[0],
    category: "Electrical · 6 min",
    title: "Older electrical systems: what should you check?",
    text: "From the distribution board and earthing to old wiring: these parts jointly determine safety and capacity.",
    body: [
      "An older electrical system is not automatically unsafe, but it should be assessed when you renovate or add more equipment. The distribution board separates the home into circuits. Circuit breakers protect against overload and short circuit, while residual-current protection adds protection when current flows along an unintended path.",
      "Do not look at the board in isolation. Earthing, cables, connections and routes form one system. Older homes may contain loose or deteriorated connections and wiring with ageing insulation. A local patch is not always the best answer; a new, clearly planned route may be safer and easier to extend.",
      "Required capacity depends on simultaneous use. Induction cooking, ovens, heat pumps, EV chargers and other heavy loads may require a dedicated circuit or an upgraded supply. List current and future equipment before walls and floors are finished.",
      "Finishing is part of the decision. Concealed wiring looks clean but often requires chasing and repair. Surface-mounted wiring costs less and stays accessible. A crawl space or existing shaft may provide a tidy route with less demolition.",
      "Have alterations designed, connected and verified by a qualified electrician. NEN 1010 is the central Dutch standard for new low-voltage installations and for alterations and extensions. Extending an existing system can also require work to the affected existing section.",
    ],
    headings: ["Start with the complete system", "Check more than the distribution board", "Map future demand", "Choose a suitable cable route", "Have alterations verified"],
  },
  {
    ...knowledgeArticlesNl[1],
    category: "Interior doors · 5 min",
    title: "Door hardware in older homes",
    text: "Drooping handles, non-standard lock sizes and worn hinges often need bespoke work instead of a standard replacement.",
    body: [
      "A drooping handle is common on older doors. A modern, heavier lever puts more strain on the spring in an old lock than the original lightweight hardware. A sprung lever may help when the surrounding timber is sound enough; if the lock is worn, full replacement is generally more durable.",
      "Old locks often differ from modern standards in backset, faceplate and recess dimensions. Start with a replacement that is as close as possible to the existing measurements. Larger differences mean filling, drilling or routing the door and repairing paintwork afterwards.",
      "A privacy lock for a bathroom or WC often needs a different mortice lock and extra routing. The strike plate in the frame usually needs adjustment too. The job is complete only when the door closes without tension, the latch engages neatly and the hardware stays firm.",
      "Worn hinges can make a door sag. Modern screw-fixed hinges are often straightforward to replace. Older integrated types may no longer be available and can require removal, followed by adapting the door and frame for new hinges.",
      "A new door is not always the easy answer. Older frames are rarely perfectly square, so a straight new door will not automatically fit neatly. For better sound insulation, a solid door, perimeter seals and possibly a drop seal may achieve more than new hardware alone.",
    ],
    headings: ["Find out why the handle droops", "Measure the existing lock", "Align lock and strike plate", "Assess the door and hinges together", "Look beyond the hardware"],
  },
  {
    ...knowledgeArticlesNl[2],
    category: "Bathroom · 7 min",
    title: "Choosing bathroom tiles and grout",
    text: "Format, dimensional accuracy, joint width and substrate determine both the finish and the maintenance required.",
    body: [
      "Large tiles create a calm appearance, use fewer joints and are often easier to clean. They do, however, require a flat substrate. Smaller tiles follow a slightly uneven wall more easily but create more grout lines. In a small room, balance levelling work, loss of space and the preferred format.",
      "The layout affects appearance and labour. A straight grid is efficient, while running-bond or diagonal patterns need more alignment and cutting. Strongly contrasting grout makes small differences in tile size and joint width more visible. Prepare a layout for sightlines, corners, niches and fittings before work begins.",
      "Rectified tiles are machined more accurately after firing and can generally use a tighter joint. They still have tolerances. Non-rectified or handmade tiles usually need wider joints to absorb size variation. Check thickness, squareness and bowing as well as length and width.",
      "A matte, floor-rated tile is generally practical underfoot; polished surfaces can be slippery and wall tiles are not automatically strong enough for floors. Natural stone and unglazed tiles may be more sensitive to moisture, stains or cleaning products and can require sealing and maintenance.",
      "Cement-based grout is common and economical but can be more sensitive to staining and discolouration. Resin or composite grout costs more, yet can be easier to maintain on heavily used or light-coloured floors. Choose grout and sealant colours together.",
      "Wet-room work starts underneath the tile. A stable and level substrate, correct waterproofing, adequate falls and careful details at thresholds, drains and pipe penetrations determine service life. Finalise materials and details before tiling begins.",
    ],
    headings: ["Match tile size to the substrate", "Prepare a layout first", "Check dimensional accuracy", "Choose for the way the room is used", "Compare grout materials", "Start beneath the tile"],
  },
  {
    ...knowledgeArticlesNl[3],
    category: "Water & plumbing · 6 min",
    title: "How to spot a hidden water leak before damage spreads",
    text: "A higher water bill, musty smell or cool damp patch may be the first warning. Here is how to assess the situation safely and methodically.",
    body: [
      "A hidden leak rarely reveals itself immediately. Watch for unexplained water use, discoloured paint or plaster, lifting skirting boards, mould and an area that remains unusually cool or damp. One sign proves little, but several signs in the same area deserve prompt attention.",
      "Make sure no water is intentionally being used, then record the water-meter reading. If it changes while taps, appliances and toilets are inactive, there may be unwanted flow. Only isolate appliances or branch valves when you know how to do so safely; the result can help a technician narrow down the affected part of the system.",
      "The visible damp patch may be some distance from the source. Water can travel along a pipe, joist or floor edge before appearing. Avoid opening a wall or ceiling at random. Moisture measurements, pressure checks and knowledge of pipe routes can often reduce the search area first.",
      "Limit further damage while you wait. For an active leak, close the main water valve, isolate electrical circuits in the wet area if this can be done safely, and move vulnerable belongings. Photograph the situation and note when it became visible; this helps with repair planning and any insurance report.",
      "Repairing the pipe is not always the end of the job. Affected materials need controlled drying before finishes can be restored. Ask for the cause to be assessed too—such as a poor joint, wear, movement or frost—so the same failure is less likely to recur elsewhere.",
    ],
    headings: ["Recognise the early signs", "Use the water meter as a first check", "Do not search only at the damp patch", "Limit further damage", "Repair the cause as well"],
    alt: "Pipework during installation work in Apeldoorn",
    sourceLabel: "Topic based on suggestions from the public project archive",
    updated: "A practical guide from Domi Installation.",
  },
  {
    ...knowledgeArticlesNl[4],
    category: "Heating · 7 min",
    title: "Which hot-water system suits your home?",
    text: "A storage cylinder, instantaneous heater and heat-pump water heater each balance comfort, space, energy and installation differently.",
    body: [
      "Start with your hot-water profile rather than a brand or power rating. How many people live in the home, how many showers follow one another, and is hot water needed in the kitchen and bathroom at the same time? Peak demand often matters more than average daily use.",
      "A storage system can deliver a substantial volume for a limited period, but needs space and loses some heat while idle. An instantaneous unit heats on demand and avoids a large cylinder, but may require considerable electrical or gas capacity. A heat-pump water heater uses ambient heat and needs suitable space, airflow and provision for noise and condensate drainage.",
      "Check what the property can support. The electrical supply, distribution board, flue or ventilation arrangement, pipe diameters and distance to outlets may restrict the options. A unit close to the main outlets reduces waiting time and distribution losses, but it must remain safely accessible for service.",
      "Compare more than purchase price. Include installation alterations, expected energy use, servicing, useful life and any space sacrificed. An efficient product that does not match the household pattern can still be uncomfortable or unnecessarily costly.",
      "Base the final choice on a survey of the property and an estimate of hot-water demand. Ask for a proposal that clearly addresses capacity, reheating time, available infrastructure and future plans. The result should still make sense after a renovation or change in household size.",
    ],
    headings: ["Map your peak demand", "Compare the three main types", "Check technical constraints", "Calculate total cost", "Plan for the home and its future"],
    alt: "Heating installation and pipework in Kampen",
    sourceLabel: "Topic based on suggestions from the public project archive",
    updated: "A selection guide from Domi Installation.",
  },
  {
    ...knowledgeArticlesNl[5],
    category: "Electrical · 6 min",
    title: "Five signs your electrical system needs attention",
    text: "Flickering lights, warm outlets and repeated trips are not minor details. They can indicate load, connection or protection problems.",
    body: [
      "Lights that repeatedly flicker or dim may point to a loose connection, faulty fitting or voltage change when a heavy appliance starts. Note when it happens and which equipment is running. That pattern helps distinguish a single lighting fault from a wider installation issue.",
      "A plug, outlet or switch should not become noticeably hot, discoloured or smell scorched. Stop using it when any of these signs appears. Remove a plug only if it is safe to do so and have the point checked before it is loaded again.",
      "A circuit breaker or residual-current device trips for a reason. A one-off overload differs from repeated failure involving the same appliance or circuit. Do not keep resetting protection without understanding the cause; that does not remove the fault.",
      "Loose outlets, damaged flexes and chains of power strips increase the risk of poor connections and overload. Temporary extension leads are not a substitute for enough fixed outlets. When a room layout or equipment changes, a planned extension is generally neater and safer.",
      "Arrange an assessment when several signs occur together, when buying an older property or before a major renovation. A competent inspection considers circuit distribution, protective devices, earthing, connections and intended load, addressing the system rather than only the visible symptom.",
    ],
    headings: ["Flickering or dimming lights", "Heat, discolouration or a scorched smell", "Protection that trips repeatedly", "Loose points and too many power strips", "Assess the system as a whole"],
    alt: "Finishing and installation work during a renovation in Rotterdam",
    sourceLabel: "Topic based on suggestions from the public project archive",
    updated: "Safety guidance from Domi Installation.",
  },
  {
    ...knowledgeArticlesNl[6],
    category: "Ventilation · 6 min",
    title: "Choosing a bathroom extractor: capacity, noise and control",
    text: "Good ventilation removes moisture without sacrificing comfort or quiet. These choices determine whether the system works in practice.",
    body: [
      "A bathroom produces a large amount of moisture in a short time. Without sufficient extraction, it remains on mirrors, sealant, walls and ceilings. The fan must suit the room and run long enough to remove the moisture peak after a shower.",
      "Required performance depends on room volume, duct length and resistance, and the available supply of dry air. A powerful fan performs poorly when the door seals completely or the duct has many bends and restrictions. Supply and extract need to be designed as one airflow path.",
      "Consider noise in the real installation. A quiet motor helps, but vibration, a narrow duct or poorly mounted backdraught shutter can still be audible. Position, duct material and mounting matter as much as the number on the packaging.",
      "An overrun timer keeps extraction running after use. A humidity sensor responds to rising moisture and helps when users forget to switch ventilation on. Linking the fan to the light is simple but does not always provide the right run time. Match the control method to how the room is used.",
      "Check where the air ultimately goes. Discharging into a closed loft or crawl space simply moves the moisture problem. Use a suitable route outdoors or connect correctly to the existing ventilation system. Bathroom electrical connections also need equipment and installation suited to the relevant safety zones.",
    ],
    headings: ["Remove the full moisture peak", "Calculate more than room volume", "Control noise at its source", "Choose a suitable control method", "Complete the extract route"],
    alt: "Finished bathroom in Amsterdam",
    sourceLabel: "Topic based on suggestions from the public project archive",
    updated: "A practical ventilation guide from Domi Installation.",
  },
  {
    ...knowledgeArticlesNl[7],
    category: "Maintenance · 5 min",
    title: "Leak or burst pipe: what should you do first?",
    text: "A calm sequence limits water and consequential damage. These are the steps to take before professional help arrives.",
    body: [
      "Put people first. Do not stand in water if electrical equipment, outlets or distribution equipment may be wet. If there is immediate danger, a gas smell or an uncontrollable situation, leave the area and contact the appropriate emergency service.",
      "Stop the water supply next. The main valve is often close to the water meter, but its exact position varies. Make sure everyone in the household knows its location and occasionally check that it can be operated. A local isolation valve may be enough for a single appliance.",
      "Limit the spread with containers and absorbent material and move furniture, electronics and valuables. Do not puncture a wet ceiling without assessment: stored water and loose material can fall suddenly. Keep people clear until the structure has been checked.",
      "Record the situation with photographs and short notes, but put safety ahead of documentation. Note when the leak began, which valve was closed and which rooms are affected. When calling, explain whether water is still flowing, where the isolator is and whether electricity may be involved.",
      "An emergency repair stops the immediate leak; drying and restoration come next. Check which materials became wet and whether connections, insulation, floors or walls need follow-up work. Finally, prepare a simple emergency card listing the main valve, electrical panel and important telephone numbers.",
    ],
    headings: ["Check for immediate danger", "Isolate the water supply", "Limit spread without adding risk", "Document the situation", "Plan drying and permanent repair"],
    alt: "Installation work on pipework in Apeldoorn",
    sourceLabel: "Topic based on suggestions from the public project archive",
    updated: "An emergency checklist from Domi Installation.",
  },
] as const satisfies readonly KnowledgeArticle[];

export function findKnowledgeArticle(locale: "nl" | "en", slug: string) {
  const articles = locale === "nl" ? knowledgeArticlesNl : knowledgeArticlesEn;
  return articles.find((article) => article.slug === slug);
}
